### PR TITLE
Tray icon

### PR DESCRIPTION
**Pull request by margus234**
dependencies.py is questionable solution for not cluttering __main__.py with dependencies creation code, feel free to suggest something better

### CODE REVIEW

**Comment by KatreMetsvahi** [comment]
Saan sellise vea:
** (keycat:18526): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

Ükski notification ka ei tööta. Aga ikoon on olemas.

**Comment by KatreMetsvahi** [comment]
Ok, sellest veast sain lahti, kui kirjutasin export NO_AT_BRIDGE=1, tuleb välja, et see oli ainult warning. Aga tegelik viga:
FailedBackendError: Forced backend not found, or cannot be loaded:imagemagick

**Comment by margus234** [comment]
proovi sudo apt-get install imagemagick ja ma isegi uuendasin readme :)

**Comment by KatreMetsvahi** [comment]
Tõepoolest, nüüd on korras, minu viga :)

**Pull request merged**
